export const CuiIconNames = {
  control: {
    type: 'select',
    options: [
      'alert',
      'checkmarkCircle2',
      'chevronRight',
      'heart',
      'messageCircle',
      'menu',
      'plus',
      'percent',
      'star',
      'allDone',
      'slickPrev',
      'slickNext',
      'retweet',
      'arrowLeft',
      // new icons
      'easyAndConvenient',
      'eggsAndDairy',
      'everChangingMenu',
      'favorite',
      'favorites',
      'featured',
      'filter',
      'fire',
      'flexiblePlans',
      'glutenFree',
      'handCrafted',
      'highCalories',
      'highFat',
      'highProtein',
      'history',
      'hundreds',
      'infoIcon',
      'keto',
      'lowCalories',
      'lowCarbs',
      'lowFat',
      'lowSodium',
      'lowSugar',
      'meals',
      'meat',
      'mixMatch',
      'nutFree',
      'orders1',
      'orders2',
      'orders3',
      'orders4',
      'paleo',
      'plantBased',
      'pork',
      'poultry1',
      'poultry2',
      'reviewStars1',
      'reviewStars2',
      'seafood',
      'small',
      'sorting',
      'soyFree',
      'spicyIcon',
      'spicy',
      'superFood1',
      'superFood2',
      'vegan',
      'vegetarian2',
      'vegetarian',
      'verySpicy',
      'warning',
      'youVeTried',
      'yourTopRated'
    ]
  },
  defaultValue: 'heart'
}

const imageUrl = filename =>
  `https://static.cookunity.com/cross/front-lib/icons/${filename}`

export const icons = {
  alert: imageUrl('alert-circle.svg'),
  checkmarkCircle2: imageUrl('checkmark-circle-2.svg'),
  chevronRight: imageUrl('chevron-right.svg'),
  heart: imageUrl('heart.svg'),
  messageCircle: imageUrl('message-circle.svg'),
  menu: imageUrl('menu.svg'),
  plus: imageUrl('plus.svg'),
  percent: imageUrl('percent.svg'),
  star: imageUrl('star.svg'),
  starFull: imageUrl('star-full.svg'),
  alertTriangle: imageUrl('alert-triangle.svg'),
  trash: imageUrl('trash.svg'),
  info: imageUrl('info.svg'),
  chevronUp: imageUrl('chevron-up.svg'),
  chevronDown: imageUrl('chevron-down.svg'),
  cart: imageUrl('shopping-cart.svg'),
  allDone: imageUrl('all-done.svg'),
  slickPrev: imageUrl('slick-prev.svg'),
  slickNext: imageUrl('slick-next.svg'),
  sync: imageUrl('sync.svg'),
  retweet: imageUrl('retweet.svg'),
  arrowLeft: imageUrl('arrow-left.svg'),
  // new icons
  easyAndConvenient: imageUrl('easy-and-convenient.svg'),
  eggsAndDairy: imageUrl('eggs-and-dairy.svg'),
  everChangingMenu: imageUrl('ever-changing-menu.svg'),
  favorite: imageUrl('favorite-icon.svg'),
  favorites: imageUrl('favorites.svg'),
  featured: imageUrl('featured.svg'),
  filter: imageUrl('filter.svg'),
  fire: imageUrl('fire.svg'),
  flexiblePlans: imageUrl('flexible-plans.svg'),
  glutenFree: imageUrl('gluten-free.svg'),
  handCrafted: imageUrl('hand-crafted.svg'),
  highCalories: imageUrl('high-calories.svg'),
  highFat: imageUrl('high-fat.svg'),
  highProtein: imageUrl('high-protein.svg'),
  history: imageUrl('history.svg'),
  hundreds: imageUrl('hundreds.svg'),
  infoIcon: imageUrl('info-icon.svg'),
  keto: imageUrl('keto.svg'),
  lowCalories: imageUrl('low-calories.svg'),
  lowCarbs: imageUrl('low-carbs.svg'),
  lowFat: imageUrl('low-fat.svg'),
  lowSodium: imageUrl('low-sodium.svg'),
  lowSugar: imageUrl('low-sugar.svg'),
  meals: imageUrl('meals.svg'),
  meat: imageUrl('meat.svg'),
  mixMatch: imageUrl('mix-match.svg'),
  nutFree: imageUrl('nut-free.svg'),
  orders1: imageUrl('orders-1.svg'),
  orders2: imageUrl('orders-2.svg'),
  orders3: imageUrl('orders-3.svg'),
  orders4: imageUrl('orders-4.svg'),
  paleo: imageUrl('paleo.svg'),
  plantBased: imageUrl('plant-based.svg'),
  pork: imageUrl('pork.svg'),
  poultry1: imageUrl('poultry-1.svg'),
  poultry2: imageUrl('poultry-2.svg'),
  reviewStars1: imageUrl('review-stars-1.svg'),
  reviewStars2: imageUrl('review-stars-2.svg'),
  seafood: imageUrl('seafood.svg'),
  small: imageUrl('small.svg'),
  sorting: imageUrl('sorting.svg'),
  soyFree: imageUrl('soy-free.svg'),
  spicyIcon: imageUrl('spicy-icon.svg'),
  spicy: imageUrl('spicy.svg'),
  superFood1: imageUrl('super-food-1.svg'),
  superFood2: imageUrl('super-food-2.svg'),
  vegan: imageUrl('vegan.svg'),
  vegetarian2: imageUrl('vegetarian-2.svg'),
  vegetarian: imageUrl('vegetarian-icon.svg'),
  verySpicy: imageUrl('very-spicy.svg'),
  warning: imageUrl('warning-icon.svg'),
  youVeTried: imageUrl('you_ve-tried.svg'),
  yourTopRated: imageUrl('your-top-rated.svg')
}
